import { ImageService, Header } from "../image.service";
export declare class ImageUploadComponent {
    private imageService;
    visible: boolean;
    private visibleAnimate;
    max: number;
    url: string;
    headers: Header[];
    preview: boolean;
    acceptTypes: string[];
    styling: string;
    quality: string;
    input: any;
    private isPending;
    private onFileUploadFinish;
    private onRemove;
    private errMsg;
    private errMsgShow;
    private files;
    private fileCounter;
    private pendingFilesCounter;
    private isFileOver;
    private buttonCaption;
    private uploadButtonCaption;
    private dropBoxMessage;
    constructor(imageService: ImageService);
    ngOnInit(): void;
    fileChange(files: any): void;
    private uploadFiles(files, filesToUploadNum);
    private uploadSingleFile(fileHolder);
    private deleteFile(file);
    fileOver(isOver: any): void;
    private countRemainingSlots();
    readonly value: any[];
    modal(): void;
    show(): void;
    hide(): void;
    send(val: string): void;
}
