/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/common/src/localization';
import * as import4 from './image.service';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/i18n/tokens';
import * as import7 from '@angular/http/src/http';
class OutgrowFileUploadModuleInjector extends import0.NgModuleInjector<import1.OutgrowFileUploadModule> {
  _CommonModule_0:import2.CommonModule;
  _OutgrowFileUploadModule_1:import1.OutgrowFileUploadModule;
  __NgLocalization_2:import3.NgLocaleLocalization;
  __ImageService_3:import4.ImageService;
  constructor(parent:import5.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import3.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import3.NgLocaleLocalization(this.parent.get(import6.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  get _ImageService_3():import4.ImageService {
    if ((this.__ImageService_3 == null)) { (this.__ImageService_3 = new import4.ImageService(this.parent.get(import7.Http))); }
    return this.__ImageService_3;
  }
  createInternal():import1.OutgrowFileUploadModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._OutgrowFileUploadModule_1 = new import1.OutgrowFileUploadModule();
    return this._OutgrowFileUploadModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.OutgrowFileUploadModule)) { return this._OutgrowFileUploadModule_1; }
    if ((token === import3.NgLocalization)) { return this._NgLocalization_2; }
    if ((token === import4.ImageService)) { return this._ImageService_3; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const OutgrowFileUploadModuleNgFactory:import0.NgModuleFactory<import1.OutgrowFileUploadModule> = new import0.NgModuleFactory(OutgrowFileUploadModuleInjector,import1.OutgrowFileUploadModule);